[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'chase/vim-ansible-yaml'

[[plugins]]
repo = 'vim-airline/vim-airline'
