[[plugins]]
repo = 'Shougo/deoplete.nvim'
""on_i = 1
""hook_add = '''
""let g:deoplete#enable_at_startup = 1
""'''

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if = "!has('nvim')"

[[plugins]]
repo = 'roxma/nvim-yarp'
if = "!has('nvim')"

